### ISSUE TITLE
Basic completion error

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#1005]
I have a configuration file that uses basic completion. Every time it attempts to provide completion it gives an error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ASCompletion.Completion.ASComplete.GetExpression(ScintillaControl Sci, Int32 position, Boolean ignoreWhiteSpace)
   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility)
   at ASCompletion.Completion.ASGenerator.GetStatementReturnType(ScintillaControl Sci, ClassModel inClass, String line, Int32 startPos)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PostfixCodeCompletion.Helpers.Reflector.ASGeneratorGetStatementReturnType(ScintillaControl sci, String line, Int32 positionFromLine)
   at PostfixCodeCompletion.PluginMain.GetPostfixCompletionExpr()
   at PostfixCodeCompletion.PluginMain.OnCompletionListVisibleChanged(Object o, EventArgs args)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at PluginCore.Controls.CompletionList.FadeIn()
   at PluginCore.Controls.UITools.PreFilterMessage(Message& m)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

Or this one:
```
Exception has been thrown by the target of an invocation.

   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PostfixCodeCompletion.Helpers.Reflector.ASGeneratorGetStatementReturnType(ScintillaControl sci, String line, Int32 positionFromLine)
   at PostfixCodeCompletion.PluginMain.GetPostfixCompletionExpr()
   at PostfixCodeCompletion.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

I use a development build

![image](https://cloud.githubusercontent.com/assets/576184/11837484/82b1ece0-a3e1-11e5-858d-305438838c5b.png)

**Comment by Neverbirth** [comment]
By basic completion you mean this is a Haxe project and you are using only the built in FD completion mode instead of the compiler service?

**Comment by Meychi** [comment]
Are you using PostfixCodeCompletion plugin from @SlavaRa?

**Comment by SlavaRa** [comment]
It's my fault, I will fix it maybe tomorrow, sorry

**Comment by markknol** [comment]
@Neverbirth Yes and no. The type of the project is Haxe, but the file that is open uses syntax of "properties". That uses basic completion from anything he can get out of that file.
