### ISSUE TITLE
[haxedevelop] `import haxe.ds.Option` crashes "sometimes"

### ISSUE THREAD

**Issue by Simn** [fdorg/flashdevelop#1098]
I have Main.hx open and try to type `import.haxe.ds.Option`. This randomly crashes on the "d" or the "O" with the following message:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PluginCore.Controls.CompletionList.FindWordStartingWith(String word)
   at PluginCore.Controls.CompletionList.OnChar(ScintillaControl sci, Int32 value)
   at PluginCore.Controls.UITools.OnChar(ScintillaControl sci, Int32 value)
   at ScintillaNet.CharAddedHandler.Invoke(ScintillaControl sender, Int32 ch)
   at ScintillaNet.ScintillaControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8669 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
FlashDevelop
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/HaxeDevelop.exe
----------------------------------------
PluginCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/PluginCore.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8681 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8679 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.8674 built by: QFE
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AirProperties
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/AirProperties.DLL
----------------------------------------
AS2Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/AS2Context.DLL
----------------------------------------
ASCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/ASCompletion.DLL
----------------------------------------
AS3Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/AS3Context.DLL
----------------------------------------
XMLCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/XMLCompletion.DLL
----------------------------------------
Aga
    Assembly Version: 1.7.0.1
    Win32 Version: 1.7.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Aga.DLL
----------------------------------------
ASClassWizard
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/ASClassWizard.DLL
----------------------------------------
BasicCompletion
    Assembly Version: 1.0.0.32508
    Win32 Version: 1.0.0.32508
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/BasicCompletion.DLL
----------------------------------------
BookmarkPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/BookmarkPanel.DLL
----------------------------------------
BridgeSettings
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/BridgeSettings.DLL
----------------------------------------
CodeAnalyzer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/CodeAnalyzer.DLL
----------------------------------------
CodeFormatter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/CodeFormatter.DLL
----------------------------------------
Antlr3
    Assembly Version: 3.1.3.42154
    Win32 Version: 3.1.3.42154
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Antlr3.DLL
----------------------------------------
CodeRefactor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/CodeRefactor.DLL
----------------------------------------
CssCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/CssCompletion.DLL
----------------------------------------
DataEncoder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/DataEncoder.DLL
----------------------------------------
fdb.j4n
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/fdb.j4n.DLL
----------------------------------------
jni4net.n-0.8.8.0
    Assembly Version: 0.8.8.0
    Win32 Version: 0.8.8.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/jni4net.n-0.8.8.0.DLL
----------------------------------------
FileExplorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/FileExplorer.DLL
----------------------------------------
FlashConnect
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/FlashConnect.DLL
----------------------------------------
FlashDebugger
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/FlashDebugger.DLL
----------------------------------------
FlashLogViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/FlashLogViewer.DLL
----------------------------------------
FlashViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/FlashViewer.DLL
----------------------------------------
ProjectManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/ProjectManager.DLL
----------------------------------------
HaXeContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/HaXeContext.DLL
----------------------------------------
jni4net.n-0.8.4.0
    Assembly Version: 0.8.4.0
    Win32 Version: 0.8.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/jni4net.n-0.8.4.0.DLL
----------------------------------------
jni4net.n.w32.v20-0.8.4.0
    Assembly Version: 0.8.4.0
    Win32 Version: 0.8.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/jni4net.n.w32.v20-0.8.4.0.DLL
----------------------------------------
jni4net.n.w32.v20-0.8.8.0
    Assembly Version: 0.8.8.0
    Win32 Version: 0.8.8.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/jni4net.n.w32.v20-0.8.8.0.DLL
----------------------------------------
LayoutManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/LayoutManager.DLL
----------------------------------------
System.Design
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Design/2.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
LoomContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/LoomContext.DLL
----------------------------------------
MacroManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/MacroManager.DLL
----------------------------------------
OutputPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/OutputPanel.DLL
----------------------------------------
PHPContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/PHPContext.DLL
----------------------------------------
SwfOp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/SwfOp.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
ResultsPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/ResultsPanel.DLL
----------------------------------------
SourceControl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/SourceControl.DLL
----------------------------------------
StartPage
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/StartPage.DLL
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
TaskListPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/HaxeDevelop/Plugins/TaskListPanel.DLL
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
o4qg6ra9
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
0s_ibr4e
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
r_uiegbs
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Non-default settings include:

Completion List Insertion Triggers: \t\n
Automatically Reload Modified Files: True
Trim Trailing Whitespace: True
Coding Style Type: BracesOnLine

**Comment by Simn** [comment]
I recompiled FD and can no longer reproduce the problem, so I probably was on some weird HD version or something.
