### ISSUE TITLE
Find and Replace - RegExp exception

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1183]
Create a new document with these contents:

```
text
text
text
```

Open `Find and Replace` dialog, check `Regular expressions` checkbox.
Enter `([a-z]+)` as search text.
Enter `\1` as replacement text (since you're a `sed` user and keep forgetting that FD expects `$1`).
Click `Find next`, then `Replace` (or `Replace` twice). Here you notice that `text` got replaced with `\1` - not what you wanted, so change replacement text to `$1`, then click `Replace` again.

Enjoy the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at PluginCore.FRService.FRSearch.ExpandGroups(String text, SearchMatch match)
   at FlashDevelop.Dialogs.FRInDocDialog.GetReplaceText(SearchMatch match)
   at FlashDevelop.Dialogs.FRInDocDialog.ReplaceButtonClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at System.Windows.Forms.Button.ProcessMnemonic(Char charCode)
   at System.Windows.Forms.ContainerControl.ProcessMnemonic(Char charCode)
   at System.Windows.Forms.Form.ProcessMnemonic(Char charCode)
   at System.Windows.Forms.ContainerControl.ProcessDialogChar(Char charCode)
   at System.Windows.Forms.Form.ProcessDialogChar(Char charCode)
   at System.Windows.Forms.Control.ProcessDialogChar(Char charCode)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

If `Find Next` is clicked first, then clicking `Replace` doesn't make an exception. If parenthetical groups are not used in the replacement text, there's also no exception.

**Comment by gene-pavlovsky** [comment]
I've done a small investigation and found the cause of this bug:
FRInDocDialog.ReplaceButtonClick has this logic
```cs
            if (sci.SelText.Length == 0) this.FindNext(true);
            else
            {
                String replaceWith = this.GetReplaceText(currentMatch);
```

This assumes that if there's a selected text, `currentMatch` must be valid, which is not necessarily the case.
A use may select some text manually, or it might be a selection from previous search, but changing the search query or replacement text resets `currentMatch` to null.

**Comment by gene-pavlovsky** [comment]
I tested the PR and couldn't find issues so far
