### ISSUE TITLE
Project panel - clicking on class while exploring SWF results in an exception

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1188]
When I'm browsing classes or symbols inside a compiled SWF in the project panel, if I click on any class or symbol in the tree, I get this exception:

```
The given path's format is not supported.

   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at CodeRefactor.PluginMain.OnTreeSelectionChanged()
   at CodeRefactor.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

**Comment by SlavaRa** [comment]
it will be fixed it today, sorry

**Comment by gene-pavlovsky** [comment]
Thanks!
