### ISSUE TITLE
[Haxe] random NullReferenceException during auto completion

### ISSUE THREAD

**Issue by sebthom** [fdorg/flashdevelop#1243]
Since the version 5.1.1.1 I randomly receive an Exception popup when auto completion kicks in. I could not figure out a reproducible usage pattern to trigger it. It just pops up annoyingly often. Maybe it's some kind of race condition.

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PluginCore.Controls.CompletionList.FindWordStartingWith(String word)
   at PluginCore.Controls.CompletionList.OnChar(ScintillaControl sci, Int32 value)
   at PluginCore.Controls.UITools.OnChar(ScintillaControl sci, Int32 value)
   at ScintillaNet.CharAddedHandler.Invoke(ScintillaControl sender, Int32 ch)
   at ScintillaNet.ScintillaControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8689 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
FlashDevelop
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/FlashDevelop.exe
----------------------------------------
PluginCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/PluginCore.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8690 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8681 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8679 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.8693 built by: QFE
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AirProperties
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/AirProperties.DLL
----------------------------------------
AntPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/AntPanel.DLL
----------------------------------------
AS2Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/AS2Context.DLL
----------------------------------------
ASCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/ASCompletion.DLL
----------------------------------------
AS3Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/AS3Context.DLL
----------------------------------------
XMLCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/XMLCompletion.DLL
----------------------------------------
Aga
    Assembly Version: 1.7.0.1
    Win32 Version: 1.7.0.1
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Aga.DLL
----------------------------------------
ASClassWizard
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/ASClassWizard.DLL
----------------------------------------
BasicCompletion
    Assembly Version: 1.0.0.18867
    Win32 Version: 1.0.0.18867
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/BasicCompletion.DLL
----------------------------------------
BookmarkPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/BookmarkPanel.DLL
----------------------------------------
BridgeSettings
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/BridgeSettings.DLL
----------------------------------------
CodeAnalyzer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/CodeAnalyzer.DLL
----------------------------------------
CodeFormatter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/CodeFormatter.DLL
----------------------------------------
Antlr3
    Assembly Version: 3.1.3.42154
    Win32 Version: 3.1.3.42154
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Antlr3.DLL
----------------------------------------
CodeRefactor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/CodeRefactor.DLL
----------------------------------------
CssCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/CssCompletion.DLL
----------------------------------------
CustomizeToolbar
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/CustomizeToolbar.DLL
----------------------------------------
DataEncoder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/DataEncoder.DLL
----------------------------------------
ExportProject
    Assembly Version: 1.0.0.30925
    Win32 Version: 1.0.0.30925
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/ExportProject.DLL
----------------------------------------
fdb.j4n
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/fdb.j4n.DLL
----------------------------------------
jni4net.n-0.8.8.0
    Assembly Version: 0.8.8.0
    Win32 Version: 0.8.8.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/jni4net.n-0.8.8.0.DLL
----------------------------------------
FileExplorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/FileExplorer.DLL
----------------------------------------
FlashConnect
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/FlashConnect.DLL
----------------------------------------
FlashDebugger
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/FlashDebugger.DLL
----------------------------------------
FlashLogViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/FlashLogViewer.DLL
----------------------------------------
FlashViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/FlashViewer.DLL
----------------------------------------
HaXeContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/HaXeContext.DLL
----------------------------------------
HaxeUILayoutPreview
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/HaxeUILayoutPreview.DLL
----------------------------------------
HighlightSelection
    Assembly Version: 1.0.0.32426
    Win32 Version: 1.0.0.32426
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/HighlightSelection.DLL
----------------------------------------
InterfaceSuggest
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/InterfaceSuggest.DLL
----------------------------------------
Interfaciator
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/Interfaciator.DLL
----------------------------------------
jni4net.n.w32.v20-0.8.8.0
    Assembly Version: 0.8.8.0
    Win32 Version: 0.8.8.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/jni4net.n.w32.v20-0.8.8.0.DLL
----------------------------------------
LayoutManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/LayoutManager.DLL
----------------------------------------
System.Design
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Design/2.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
LoomContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/LoomContext.DLL
----------------------------------------
ProjectManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/ProjectManager.DLL
----------------------------------------
MacroManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/MacroManager.DLL
----------------------------------------
NavigationBar
    Assembly Version: 2.5.1.0
    Win32 Version: 2.5.1.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/NavigationBar.DLL
----------------------------------------
OutputPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/OutputPanel.DLL
----------------------------------------
PHPContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/PHPContext.DLL
----------------------------------------
PreviousEdit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/PreviousEdit.DLL
----------------------------------------
SwfOp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/SwfOp.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
ResultsPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/ResultsPanel.DLL
----------------------------------------
SgmlReaderDll
    Assembly Version: 1.8.2.26452
    Win32 Version: 1.8.2.26452
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/SgmlReaderDll.DLL
----------------------------------------
SourceControl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/SourceControl.DLL
----------------------------------------
StartPage
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/StartPage.DLL
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
TaskListPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/apps/dev/haxe/flashdevelop/Plugins/TaskListPanel.DLL
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
9hh90i1o
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.50727.8690 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing.Design
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing.Design/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.Design.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
```

**Comment by sebthom** [comment]
I am now also getting the following exception. Not sure if they are related.
```
Cannot access a disposed object.

   at System.Threading.TimerBase.ChangeTimer(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(Int32 dueTime, Int32 period)
   at System.Timers.Timer.UpdateTimer()
   at System.Timers.Timer.set_Interval(Double value)
   at PluginCore.Controls.CompletionList.Show(List`1 itemList, Boolean autoHide)
   at PluginCore.Controls.CompletionList.Show(List`1 itemList, Boolean autoHide, String select)
   at ASCompletion.Completion.ASComplete.HandleDotCompletion(ScintillaControl Sci, Boolean autoHide)
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl Sci, Int32 Value, Boolean autoHide)
```

**Comment by Neverbirth** [comment]
The second exception may be related to another problem that was already identified a couple of months ago, but I think it's still not fixed.

For the first one, what if you run without any 3rd party plugin? Did you give it a try?

**Comment by Neverbirth** [comment]
After all this time, I happened to stumble onto a machine that throwed this error. The error was caused by a wrong project setup resulting in some strange compiler service result. The project also showed some strange behaviour in some parts of code, it didn't make any sense. Sadly this was a computer without admin rights and a project I don't have access to, so I couldn't fiddle a lot, but hopefully I saw enough to reproduce and fix this issue.

**Comment by Neverbirth** [comment]
Sadly I couldn't reproduce the exact same error for now. I could reproduce the parts of code where FD were behaving in a strange way, and I can confirm that one works fine in latest FD versions.

**Comment by Neverbirth** [comment]
I could find the way to reproduce this error in FD 5.1, but I couldn't reproduce in FD 5.2. I would need to find the source of the error in 5.1 to know if this can happen in 5.2 at all.

**Comment by SlavaRa** [comment]
FD 5.2.1.3
![issue1243](https://cloud.githubusercontent.com/assets/1700940/19020880/7ee8bc08-88bd-11e6-98cd-3061516c6eea.gif)

**Comment by sebthom** [comment]
I am not seeing this issue in FD5.3 anymore.
