### ISSUE TITLE
The FixedSizeQueue has zero capacity.

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#1612]
```
System.InvalidOperationException: The FixedSizeQueue has zero capacity.
   at PluginCore.Collections.FixedSizeQueue`1.Enqueue(T item)
   at FlashDevelop.Managers.ClipboardManager.HandleWndProc(Message& m)
   at FlashDevelop.MainForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
@wise0704 5.2.172 development

**Comment by wise0704** [comment]
This issue occurs when the settings file is changed randomly and externally (i.e. by git), and the Clipboard History Size is set to 0 (minimum allowed through settings dialogue is 1).

I'll submit a fix today.
