### ISSUE TITLE
[Haxe][ASGenerator] Runtime error `Object reference not set to an instance of an object.` after execution `Generate interface definition` for get|set

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#1743]
```haxe
package;
interface IFoo {
	var foo(g|et, null):haxe.Timer->haxe.ds.Vector<Int>; // | <-- cursor
}
```
```
Object reference not set to an instance of an object.

   at ASCompletion.Completion.ASGenerator.GenerateFunctionJob(GeneratorJobType job, ScintillaControl sci, MemberModel member, Boolean detach, ClassModel inClass) in C:\projects\opensource\flashdevelop\External\Plugins\ASCompletion\Completion\ASGenerator.cs:line 2830
   at ASCompletion.Completion.ASGenerator.GenerateJob(GeneratorJobType job, MemberModel member, ClassModel inClass, String itemLabel, Object data) in C:\projects\opensource\flashdevelop\External\Plugins\ASCompletion\Completion\ASGenerator.cs:line 953
   at ASCompletion.Completion.GeneratorItem.get_Value() in C:\projects\opensource\flashdevelop\External\Plugins\ASCompletion\Completion\ASGenerator.cs:line 4791
   at PluginCore.Controls.CompletionList.ReplaceText(ScintillaControl sci, String tail, Char trigger) in C:\projects\opensource\flashdevelop\PluginCore\PluginCore\Controls\CompletionList.cs:line 810
   at PluginCore.Controls.CompletionList.ReplaceText(ScintillaControl sci, Char trigger) in C:\projects\opensource\flashdevelop\PluginCore\PluginCore\Controls\CompletionList.cs:line 788
   at PluginCore.Controls.CompletionList.HandleKeys(ScintillaControl sci, Keys key) in C:\projects\opensource\flashdevelop\PluginCore\PluginCore\Controls\CompletionList.cs:line 900
   at PluginCore.Controls.UITools.HandleKeys(Keys key) in C:\projects\opensource\flashdevelop\PluginCore\PluginCore\Controls\UITools.cs:line 458
   at PluginCore.Controls.UITools.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority) in C:\projects\opensource\flashdevelop\PluginCore\PluginCore\Controls\UITools.cs:line 145
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e) in C:\projects\opensource\flashdevelop\PluginCore\PluginCore\Managers\EventManager.cs:line 122
```

**Comment by SlavaRa** [comment]
Depends on #1564

**Comment by Neverbirth** [comment]
Are you sure it's 1564?

**Comment by SlavaRa** [comment]
Oh, typo... fixed :)
