### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by ncannasse** [fdorg/flashdevelop#1808]
Latest HaxeDevelop often crashes at startup (never had the case with previous version).

Here's what I found in Exceptions.log:

```
Unhandled exception: 

System.Exception: System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à HaXeContext.HaxeComplete.<>c__DisplayClass22_0`1.<StartThread>b__0(Object _)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by markknol** [comment]
I also have it, seems to be related to Haxe 4 projects. it works when you start a non-haxe 4 project file.

Here a dump from my Exceptions.log:
```



Unhandled exception: 

System.Exception: System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility)
   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace)
   at QuickNavigate.ControlClickManager.ProcessMouseMove(Point point)
   at QuickNavigate.ControlClickManager.MouseHookProc(Int32 nCode, IntPtr wParam, IntPtr lParam)


Unhandled exception: 

System.Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at HaXeContext.Context.ResolveType(String cname, FileModel inFile)
   at ASCompletion.Model.ClassModel.ResolveExtendedType()
   at ASCompletion.Model.ClassModel.ResolveExtends()
   at ASCompletion.Completion.ASComplete.FindMember(String token, ClassModel inClass, ASResult result, FlagType mask, Visibility acc)
   at ASCompletion.Completion.ASComplete.EvalVariable(String token, ASExpr local, FileModel inFile, ClassModel inClass)
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility)
   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace)
   at QuickNavigate.ControlClickManager.ProcessMouseMove(Point point)
   at QuickNavigate.ControlClickManager.MouseHookProc(Int32 nCode, IntPtr wParam, IntPtr lParam)
```

**Comment by Neverbirth** [comment]
@chipshort

**Comment by ncannasse** [comment]
This might be related in change in Haxe 4 : unless you compile with `-D old-error-format` all compiler errors and display completion are reported in UTF8 position in file with 1-based column (was Binary position and 0-based column in 3.x)

**Comment by ncannasse** [comment]
You can test by downloading Haxe 4 from here : https://haxe.org/download/version/4.0.0-preview.2/

**Comment by Neverbirth** [comment]
@markknol for the second exception you've posted I could get a repro, I will do my best to fix it during this day... my days lately are like a roller-coaster heh.

**Comment by Neverbirth** [comment]
I pushed a change that should fix your second exception @markknol. With the projects I have here I couldn't repro it, so even if I'm confident I won't say it solves it 100%. I wonder if your first exception is some bug specific to QuickNavigate as I see it in the stacktrace.

I will try to reproduce and fix Nicolas' one tomorrow.

**Comment by markknol** [comment]
Hi, I tested the new build. I still have crashes at start. 
I noticed the log, but it doesn't seem to always add a line when it crashes at start. I just got few crashes, but there is no line added today.

**Comment by Neverbirth** [comment]
So by your comment I would say the crashes you are getting right now are related to something else. I will keep an eye and run more tests.

I use at work a custom build with other changes and not fully up to date, so I was not aware of these problems.

**Comment by Neverbirth** [comment]
@markknol today I saw on a colleague's PC another similar exception, I will investigate it later today.

So far I couldn't reproduce Nicola's one, but I had some busy days, also didn't try with Haxe 4 yet, maybe it's related.

**Comment by ncannasse** [comment]
Please detect Haxe 4+ and change error reporting position accordingly while
you're at it ;)

**Comment by DarthVan** [comment]
Hi! Got this bug too. biuld 5.3.1.50

**Comment by SlavaRa** [comment]
I can check it out tonight after the main job.

**Comment by YellowAfterlife** [comment]
A sample:

1. Do `haxelib install nodejs` (only happens with haxe >=4.0.0?)
2. Open [this project](https://github.com/fdorg/flashdevelop/files/1562387/abug.zip) and wait until it starts to parse lib nodejs.

Resulting exception:
```
System.Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ASCompletion.Model.ASFileParser.ParseSrc(FileModel fileModel, String ba, Boolean allowBaReExtract)
   at ASCompletion.Model.ASFileParser.ParseFile(FileModel fileModel)
   at HaXeContext.Context.GetFileModel(String fileName)
   at ASCompletion.Model.PathExplorer.ParseFoundFiles()
   at ASCompletion.Model.PathExplorer.BackgroundRun()
   at ASCompletion.Model.PathExplorer.ExploreInBackground()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Neverbirth** [comment]
Well, that's not exactly startup heh, but I know why and where it happens, I already did some work for this, hopefully I can push my local changes tomorrow.

**Comment by Neverbirth** [comment]
I pushed a change solving some crashes. I don't know if this will solve the cases you run into, I know of some other problems and have other local changes queued, but I don't have them at hand right now, they are on another PC, and have to review them. I hope I will have time during the night.

**Comment by ncannasse** [comment]
@Neverbirth I think I found one of the main crash reasons : when you close a file tab after having switched projects, it might crash (no exception stack shown)

**Comment by TerryCavanagh** [comment]
Have been getting a lot of crashes with Haxedevelop too. In my case, I'm using Haxedevelop 5.3.1.2 with Haxe 3.4.4. I get frequent crashes when starting up initially, and when saving new files.

Happy to provide any information that might be useful (I don't seem to have an Exceptions.log file on my pc)
