### ISSUE TITLE
Exception when checking out another git branch

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1816]
I have the current development branch running from Visual Studio (debug build).
I have a large Haxe project open.
Sometimes, when I switch to a different git branch, VS stops FlashDevelop with the following exception:
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Cross-thread operation not valid: Control '' accessed from a thread other than the thread it was created on.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.get_CreateThreadId()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at PluginCore.Controls.MessageBar.CreateBar(ITabbedDocument target, String message, String icon) in C:\project\flashdevelop\PluginCore\PluginCore\Controls\MessageBar.cs:line 96
   at PluginCore.Controls.MessageBar.ShowWarning(String message) in C:\project\flashdevelop\PluginCore\PluginCore\Controls\MessageBar.cs:line 73
   at ASCompletion.Model.ClassModel.ResolveExtendedType() in C:\project\flashdevelop\External\Plugins\ASCompletion\Model\ClassModel.cs:line 168
   at ASCompletion.Model.ClassModel.ResolveExtends() in C:\project\flashdevelop\External\Plugins\ASCompletion\Model\ClassModel.cs:line 119
   at ASCompletion.Helpers.ASTCache.UpdateClass(ClassModel cls, Dictionary`2 cache) in C:\project\flashdevelop\External\Plugins\ASCompletion\Helpers\ASTCache.cs:line 256
   at ASCompletion.Helpers.ASTCache.<UpdateOutdatedModels>b__10_0() in C:\project\flashdevelop\External\Plugins\ASCompletion\Helpers\ASTCache.cs:line 112
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
```

The message that FD is trying to show is "Inheritance loop detected between com.module.languageprovider.LanguageProviderModule and com.module.languageprovider.LanguageProviderModule."
By the way, the class is defined as `class LanguageProviderModule extends Module implements ILanguageProviderModule` (`Module` doesn't have a superclass), so I have no idea why would there be an inheritance loop. Needless to say, the project compiles and works.

**Comment by Neverbirth** [comment]
As I told you yesterday, note that this kind of errors only appear during debugging. But yep, I guess this shouldn't trigger a circular reference.

**Comment by gene-pavlovsky** [comment]
Yes, I got that point.
I might be wrong, but it seems like this results in loss of functionality?
If I understand correctly, ASCompletion is trying to show a warning bar, but it never appears due to this exception.

**Comment by gene-pavlovsky** [comment]
I'm getting this exception when switching branches now:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at HaXeContext.Context.ResolveImport(MemberModel item, MemberList imports) in C:\project\flashdevelop\External\Plugins\HaXeContext\Context.cs:line 956
```
