### ISSUE TITLE
as3 debugger not starting in 5.3.0.3

### ISSUE THREAD

**Issue by romamik** [fdorg/flashdevelop#1855]
I've just installed new flashdevelop version and get this error, when trying to start as3 debugger:

> Debugger startup error. For troubleshooting see: http://www.flashdevelop.org/wikidocs/index.php?title=F.A.Q
> Error details: net.sf.jni4net.jni.JNIException: Can't find jni4net.j-0.8.8.0.jar
> at c:\program files (x86)\flashdevelop\jni4net.j-0.8.8.0.jar
> or c:\program files (x86)\flashdevelop\bin\jni4net.j-0.8.8.0.jar
> or c:\program files (x86)\flashdevelop\lib\jni4net.j-0.8.8.0.jar
> or c:\program files (x86)\lib\jni4net.j-0.8.8.0.jar
> or C:\Program%20Files%20(x86)\FlashDevelop\Plugins\jni4net.j-0.8.8.0.jar
> or C:\Program%20Files%20(x86)\FlashDevelop\Plugins\bin\jni4net.j-0.8.8.0.jar
> or C:\Program%20Files%20(x86)\FlashDevelop\Plugins\lib\jni4net.j-0.8.8.0.jar
> or C:\Program%20Files%20(x86)\FlashDevelop\lib\jni4net.j-0.8.8.0.jar
>    в net.sf.jni4net.Bridge.FindJar()
>    в net.sf.jni4net.BridgeSetup.AddBridgeClassPath()
>    в net.sf.jni4net.BridgeSetup..ctor(Boolean autoAddBridgeClassPath)
>    в FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)

Required file is present at path `C:\Program Files (x86)\FlashDevelop\Plugins\jni4net.j-0.8.8.0.jar`.
Looks like search path is url encoded while it should not. 

As a temporary solution I've reinstalled FlashDevelop to `C:\FlashDevelop` and that solved the issue for me.

**Comment by SlavaRa** [comment]
Please check development build from http://flashdevelop.org/downloads/builds/

**Comment by romamik** [comment]
It works as intended in development build...

**Comment by pzahra** [comment]
Development version 5.3.1.52

> Debugger startup error. For troubleshooting see: http://www.flashdevelop.org/wikidocs/index.php?title=F.A.Q
> Error details: net.sf.jni4net.jni.JNIException: Can't load java class for flash.tools.debugger.concrete.DValue_ from classLoader sun.misc.Launcher$AppClassLoader@186d4c1 ---> java.lang.LinkageError: flash/tools/debugger/concrete/DValue_ : Unsupported major.minor version 52.0
>    at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
>    at net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
>    at java.lang.ClassLoader.loadClass(String par0)
>    at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
>    --- End of inner exception stack trace ---
>    at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
>    at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
>    at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)
> [Capturing traces with FDB]

**Comment by SlavaRa** [comment]
> Development version 5.3.1.52

FlashDevelop x86 or x64? java x86 or x64?

**Comment by pzahra** [comment]
Definitely java x86, and it would be the x86 FD, too. I'm pretty sure I didn't try the x64 FD, I've had issues with that in the past.

**Comment by Neverbirth** [comment]
Maybe this is fixed or improved in https://ci.appveyor.com/api/buildjobs/pb46pxtxd6362jce/artifacts/FlashDevelop%2FInstaller%2FBinary%2FFlashDevelopPR_1956.zip

**Comment by ghost** [comment]
Same with FD 5.3.1.27

FlashDevelop x32 (whatever version is on the forum post) with Java 6 x86
OS: Win 7 x64

Debugger startup error. For troubleshooting see: http://www.flashdevelop.org/wikidocs/index.php?title=F.A.Q
Error details: net.sf.jni4net.jni.JNIException: Can't load java class for flash.tools.debugger.concrete.DValue_ from classLoader sun.misc.Launcher$AppClassLoader@35ce36 ---> java.lang.LinkageError: flash/tools/debugger/concrete/DValue_ : Unsupported major.minor version 52.0
at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
at net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
at java.lang.ClassLoader.loadClass(String par0)
at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
--- End of inner exception stack trace ---
at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)
[Capturing traces with FDB]

**Comment by SlavaRa** [comment]
@romamik can you please latest development build?

**Comment by SeanJD** [comment]
I'm also having this issue.
I tried the latest release build and was having the below error, found this thread, assumed the latest development build may fix it but it hasn't.

I'm running the development build: 5.3.3.42 and am getting the following stack trace::

Error details: net.sf.jni4net.jni.JNIException: Can't load java class for flash.tools.debugger.concrete.DValue_ from classLoader sun.misc.Launcher$AppClassLoader@757aef ---> java.lang.LinkageError: flash/tools/debugger/concrete/DValue_ : Unsupported major.minor version 51.0
   at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
   at net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
   at java.lang.ClassLoader.loadClass(String par0)
   at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   --- End of inner exception stack trace ---
   at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
   at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
   at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)
[Capturing traces with FDB]

Any ideas how to fix? Or troubleshoot, happy to check through and post back if anyone has any ideas of how to sort...
