### ISSUE TITLE
System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Gamezpedia** [fdorg/flashdevelop#1877]
How did it happened .

1 - I opened a new project and leave old haxe project.xml file in the session.
2 - opened the new project.xml file and close the Flashdevelop
3 - restarted Windows, open the Flash develop and got this error And then it closes.

How did i solve it.

1 - Copy the` \AppData\Local\FlashDevelop\`  folder.
2 - Uninstall the Flashdevelop with Full options.
3 - After installing it replace all the folder with old settings folder **EXCEPT** the `\AppData\Local\FlashDevelop\Settings\SessionData.fdb` file
4 - make sure it is not replaced because i think it holds the old session data, i found it after installing it several times and replacing different settings.
```

Unhandled exception: 

System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at HaXeContext.HaxeComplete.<>c__DisplayClass22_0`1.<StartThread>b__0(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

**Comment by SlavaRa** [comment]
What version of FD are you using?

**Comment by Gamezpedia** [comment]
it's the latest one , 5.3.0.3

**Comment by SlavaRa** [comment]
Could you test the development build?

**Comment by Gamezpedia** [comment]
sure i will try it and update here .

**Comment by SlavaRa** [comment]
Thanks :)

**Comment by Gamezpedia** [comment]
hi , i tried the development build and i can't reproduce that again , also after reinstalling the release build it  didn't happen again but i will update if i found anything.
