### ISSUE TITLE
Exception when switching projects

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1935]
Running FD under VS in debug mode, I'm often (not always) getting exceptions when switching projects (dev project and tests project for it), or checking out another git branch.

Exception: System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'
Stack trace:
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at HaXeContext.Context.ResolveImport(MemberModel item, MemberList imports) in C:\project\flashdevelop\External\Plugins\HaXeContext\Context.cs:line 834
   at HaXeContext.Context.ResolveImports(FileModel inFile) in C:\project\flashdevelop\External\Plugins\HaXeContext\Context.cs:line 767
   at HaXeContext.Context.ResolveType(String cname, FileModel inFile) in C:\project\flashdevelop\External\Plugins\HaXeContext\Context.cs:line 939
   at ASCompletion.Model.ClassModel.ResolveExtendedType(List`1 extensionList) in C:\project\flashdevelop\External\Plugins\ASCompletion\Model\ClassModel.cs:line 139
   at ASCompletion.Model.ClassModel.ResolveExtends() in C:\project\flashdevelop\External\Plugins\ASCompletion\Model\ClassModel.cs:line 105
   at ASCompletion.Helpers.ASTCache.UpdateClass(ClassModel cls, Dictionary`2 cache) in C:\project\flashdevelop\External\Plugins\ASCompletion\Helpers\ASTCache.cs:line 256
   at ASCompletion.Helpers.ASTCache.<UpdateOutdatedModels>b__10_0() in C:\project\flashdevelop\External\Plugins\ASCompletion\Helpers\ASTCache.cs:line 112
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
```

**Comment by SlavaRa** [comment]
I think I know the problem.

**Comment by gene-pavlovsky** [comment]
Might be a separate issue, but sometimes (when checking out other branches) another exception occurs.
Exception:
Stack trace: System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at AS2Context.Context.GetModel(String package, String cname, String inPackage) in C:\project\flashdevelop\External\Plugins\AS2Context\Context.cs:line 655
   at HaXeContext.Context.ResolveType(String cname, FileModel inFile) in C:\project\flashdevelop\External\Plugins\HaXeContext\Context.cs:line 959
   at ASCompletion.Model.ClassModel.ResolveExtendedType(List`1 extensionList) in C:\project\flashdevelop\External\Plugins\ASCompletion\Model\ClassModel.cs:line 139
   at ASCompletion.Model.ClassModel.ResolveExtends() in C:\project\flashdevelop\External\Plugins\ASCompletion\Model\ClassModel.cs:line 105
   at ASCompletion.Helpers.ASTCache.UpdateClass(ClassModel cls, Dictionary`2 cache) in C:\project\flashdevelop\External\Plugins\ASCompletion\Helpers\ASTCache.cs:line 256
   at ASCompletion.Helpers.ASTCache.<UpdateCompleteCache>b__11_0() in C:\project\flashdevelop\External\Plugins\ASCompletion\Helpers\ASTCache.cs:line 165
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
```

**Comment by Neverbirth** [comment]
I definitely know the problem, but it's not a simple change if wanted to keep performance. There are many cases involved here. Everything could be locked everywhere, but I think that's an unacceptable solution.

**Comment by gene-pavlovsky** [comment]
Well you guys are very clever, you will figure out a solution :)

**Comment by Neverbirth** [comment]
I created some PR regarding this issue, but it's just a WIP I did before Christmas and couldn't continue yet.

https://github.com/fdorg/flashdevelop/pull/1936

I will try to add more information later from home regarding all the issues I found, special cases, etc.

**Comment by gene-pavlovsky** [comment]
@Neverbirth you can finish it, I have faith! We together!
