### ISSUE TITLE
[CodeRefactor] Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#1986]
```haxe
value.addEventListener(flash.events.TextEvent.TEXT_INPUT, onTextField|textInput);
function onTextFieldtextInput(?_) doChange();
```
`|` - cursor
```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at CodeRefactor.Provider.RenamingHelper.AddToQueue(Rename rename)
   at CodeRefactor.Commands.Rename.StartRename(Boolean useInline, String oldName, String newName)
   at CodeRefactor.Commands.Rename..ctor(ASResult target, Boolean outputResults, String newName, Boolean ignoreDeclarationSource, Boolean inline)
   at CodeRefactor.Provider.CommandFactory.CreateRenameCommandAndExecute(ASResult target, Boolean outputResults, String newName, Boolean ignoreDeclarationSource, Boolean inline)
   at CodeRefactor.Provider.CommandFactory.CreateRenameCommandAndExecute(ASResult target, Boolean outputResults, String newName, Boolean inline)
   at CodeRefactor.Provider.CommandFactory.CreateRenameCommandAndExecute(ASResult target, Boolean outputResults, Boolean inline)
   at CodeRefactor.PluginMain.RenameClicked(Object sender, EventArgs e)
```

**Comment by SlavaRa** [comment]
#1907
