### ISSUE TITLE
Open Resource dialog throws exception

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#2003]
I've had a project open, with a particular file open. I deleted the dir containing that file (using the Project panel), and closed the file.
Now if I press Ctrl+R to open `Open Resource`, an exception dialog appears:
```
System.UnauthorizedAccessException: Access to the path 'C:\project\path\to\the\folder\I\just\deleted' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at ProjectManager.Controls.OpenResourceForm.AddFilesInFolder(List`1 files, String folder) in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 342
   at ProjectManager.Controls.OpenResourceForm.AddFilesInFolder(List`1 files, String folder) in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 353
   at ProjectManager.Controls.OpenResourceForm.AddFilesInFolder(List`1 files, String folder) in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 353
   at ProjectManager.Controls.OpenResourceForm.AddFilesInFolder(List`1 files, String folder) in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 353
   at ProjectManager.Controls.OpenResourceForm.AddFilesInFolder(List`1 files, String folder) in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 353
   at ProjectManager.Controls.OpenResourceForm.AddFilesInFolder(List`1 files, String folder) in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 353
   at ProjectManager.Controls.OpenResourceForm.GetProjectFiles() in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 328
   at ProjectManager.Controls.OpenResourceForm.CreateFileList() in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 290
   at ProjectManager.Controls.OpenResourceForm.OpenResourceFormLoad(Object sender, EventArgs e) in C:\project\flashdevelop\External\Plugins\ProjectManager\Controls\OpenResourceForm.cs:line 178
...
```

**Comment by gene-pavlovsky** [comment]
I've also had similar error messages with "Access denied" in the file manager after deleting a directory.
For some reason sometimes Windows still shows a just deleted folder for some time, but trying to enter it or delete it again results in "Access denied".

I think it would be useful to wrap the `GetFiles` call in a try/catch to prevent an exception dialog in this case, I don't think showing an error message is useful in this case.
