### ISSUE TITLE
variable name resolves to ?name if type is function

### ISSUE THREAD

**Issue by Yanrishatum** [fdorg/flashdevelop#2022]
When local function is declared with optional type with type of function being optional function variable name resolves to `?name` instead of `name` . Only happens if declared inside local function. 

Isolated reproduction:
```haxe
function onInitialize() {
    function some(?val:Bool->Void) {
      ?val
    }
}
```

**Comment by SlavaRa** [comment]
```haxe
function foo(?|v = null) {}
```
`|` - cursor
apply `Generate private function`, `Generate public function`:
```
Object reference not set to an instance of an object.

   at ASCompletion.Completion.ASGenerator.GenerateFunctionJob(GeneratorJobType job, ScintillaControl sci, MemberModel member, Boolean detach, ClassModel inClass)
   at ASCompletion.Completion.ASGenerator.GenerateJob(GeneratorJobType job, MemberModel member, ClassModel inClass, String itemLabel, Object data)
   at ASCompletion.Completion.GeneratorItem.get_Value()
   at PluginCore.Controls.CompletionList.ReplaceText(ScintillaControl sci, String tail, Char trigger)
   at PluginCore.Controls.CompletionList.HandleKeys(ScintillaControl sci, Keys key)
   at PluginCore.Controls.UITools.HandleKeys(Keys key)
   at PluginCore.Controls.UITools.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

**Comment by SlavaRa** [comment]
```haxe
function foo(?|v = null) {}
```
`Refactoring` > `Rename` is now available
