### ISSUE TITLE
[Haxe][CodeGenerator] Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#2151]
```
Index was outside the bounds of the array.

   at ASCompletion.Completion.ASGenerator.GuessVarName(String name, String type)
   at ASCompletion.Completion.ASGenerator.AssignStatementToVar(ScintillaControl sci, ClassModel inClass, StatementReturnType returnType)
   at ASCompletion.Completion.ASGenerator.GenerateJob(GeneratorJobType job, MemberModel member, ClassModel inClass, String itemLabel, Object data)
   at ASCompletion.Completion.GeneratorItem.get_Value()
   at PluginCore.Controls.CompletionList.ReplaceText(ScintillaControl sci, String tail, Char trigger)
   at PluginCore.Controls.CompletionList.HandleKeys(ScintillaControl sci, Keys key)
   at PluginCore.Controls.UITools.HandleKeys(Keys key)
   at PluginCore.Controls.UITools.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```
```haxe
var _ = "";
_; | // | <-- cursor
```

**Comment by SlavaRa** [comment]
fixed via #2152
