### ISSUE TITLE
Path cannot be the empty string or all whitespace.

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#2446]
```
Path cannot be the empty string or all whitespace.

   at System.IO.Directory.CreateDirectory(String path)
   at PluginCore.Helpers.FileHelper.WriteFile(String file, String text, Encoding encoding, Boolean saveBOM)
   at FlashDevelop.Docking.TabbedDocument.Save(String file, String reason)
   at FlashDevelop.Docking.TabbedDocument.Save()
   at HaXeContext.HaxeComplete330.SaveFile()
   at HaXeContext.HaxeComplete.StartThread[T](HaxeCompleteResultHandler`1 callback, Func`1 resultFunc)
   at HaXeContext.HaxeComplete.GetList(HaxeCompleteResultHandler`1 callback)
   at HaXeContext.Context.ResolveDotContext(ScintillaControl sci, ASExpr expression, Boolean autoHide)
   at ASCompletion.Completion.ASComplete.HandleDotCompletion(ScintillaControl Sci, Boolean autoHide)
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl Sci, Int32 Value, Boolean autoHide)
```

![haxedevelop-error](https://user-images.githubusercontent.com/576184/46795176-cc60c200-cd49-11e8-9804-b28df1a84916.gif)

![image](https://user-images.githubusercontent.com/576184/46795247-f87c4300-cd49-11e8-9533-fc3de654dcfc.png)

Using HaxeDevelop nightly version http://www.github.com/fdorg/flashdevelop/commit/41581cca36

**Comment by markknol** [comment]
Downloaded latest nightly, it works there.
