### ISSUE TITLE
error on flashdevelop minimize (5.3.3.1)

### ISSUE THREAD

**Issue by Xgamefactory** [fdorg/flashdevelop#2513]
```
 (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: File format is not valid.
   at System.Windows.Forms.RichTextBox.StreamIn(Stream data, Int32 flags)
   at System.Windows.Forms.RichTextBox.StreamIn(String str, Int32 flags)
   at System.Windows.Forms.RichTextBox.set_Rtf(String value)
   at System.Windows.Forms.RichTextBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.RichTextBoxEx.WndProc(Message& message)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------

```

FlashDevelop 3.3.1
Windows 10

**Comment by SlavaRa** [comment]
3.3.1 ?

**Comment by Xgamefactory** [comment]
sorry forgot major version v5.3.3.1

**Comment by SlavaRa** [comment]
Can you test latest development build?
(http://flashdevelop.org/downloads/builds/)
