### ISSUE TITLE
"Exception while reporting end of background operation"

### ISSUE THREAD

**Issue by tom-seddon** [fdorg/flashdevelop#2540]
Just got this dialog when doing a Find All References. I know that's not really much to go on, to say the least, but I thought I'd pass it on.

EDIT: I've closed the issue as there have been numerous changes to CodeCOmplete.cs since the version I've got. And I don't have time to update right now.

Thanks,

--Tom

```
---------------------------

---------------------------
Exception while reporting end of background operation:
System.NullReferenceException: Object reference not set to an instance of an object.

   at HaXeContext.Completion.CodeComplete.InferVariableType(ScintillaControl sci, ASExpr local, MemberModel var) in C:\tom\github\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 254

   at ASCompletion.Completion.ASComplete.InferVariableType(ASExpr local, MemberModel var) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 3049

   at ASCompletion.Completion.ASComplete.EvalVariable(String token, ASExpr local, FileModel inFile, ClassModel inClass) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2892

   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2675

   at HaXeContext.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in C:\tom\github\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 518

   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4310

   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4294

   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4292

   at CodeRefactor.Provider.RefactoringHelper.DeclarationLookupResult(ScintillaControl Sci, Int32 position, DocumentHelper associatedDocumentHelper) in C:\tom\github\flashdevelop\External\Plugins\CodeRefactor\Provider\RefactoringHelper.cs:line 168

   at CodeRefactor.Provider.RefactoringHelper.DoesMatchPointToTarget(ScintillaControl sci, SearchMatch match, ASResult target, DocumentHelper associatedDocumentHelper) in C:\tom\github\flashdevelop\External\Plugins\CodeRefactor\Provider\RefactoringHelper.cs:line 290

   at CodeRefactor.Commands.FindAllReferences.ResolveActualMatches(FRResults results, ASResult target) in C:\tom\github\flashdevelop\External\Plugins\CodeRefactor\Commands\FindAllReferences.cs:line 156

   at CodeRefactor.Commands.FindAllReferences.FindFinished(FRResults results) in C:\tom\github\flashdevelop\External\Plugins\CodeRefactor\Commands\FindAllReferences.cs:line 111

   at PluginCore.FRService.FRRunner.BackgroundDone(Object sender, RunWorkerCompletedEventArgs e) in C:\tom\github\flashdevelop\PluginCore\PluginCore\FRService\FRRunner.cs:line 165
   at HaXeContext.Completion.CodeComplete.InferVariableType(ScintillaControl sci, ASExpr local, MemberModel var) in C:\tom\github\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 254

   at ASCompletion.Completion.ASComplete.InferVariableType(ASExpr local, MemberModel var) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 3049

   at ASCompletion.Completion.ASComplete.EvalVariable(String token, ASExpr local, FileModel inFile, ClassModel inClass) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2892

   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2675

   at HaXeContext.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in C:\tom\github\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 518

   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4310

   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4294

   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position) in C:\tom\github\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4292

   at CodeRefactor.Provider.RefactoringHelper.DeclarationLookupResult(ScintillaControl Sci, Int32 position, DocumentHelper associatedDocumentHelper) in C:\tom\github\flashdevelop\External\Plugins\CodeRefactor\Provider\RefactoringHelper.cs:line 168

   at CodeRefactor.Provider.RefactoringHelper.DoesMatchPointToTarget(ScintillaControl sci, SearchMatch match, ASResult target, DocumentHelper associatedDocumentHelper) in C:\tom\github\flashdevelop\External\Plugins\CodeRefactor\Provider\RefactoringHelper.cs:line 290

   at CodeRefactor.Commands.FindAllReferences.ResolveActualMatches(FRResults results, ASResult target) in C:\tom\github\flashdevelop\External\Plugins\CodeRefactor\Commands\FindAllReferences.cs:line 156

   at CodeRefactor.Commands.FindAllReferences.FindFinished(FRResults results) in C:\tom\github\flashdevelop\External\Plugins\CodeRefactor\Commands\FindAllReferences.cs:line 111

   at PluginCore.FRService.FRRunner.BackgroundDone(Object sender, RunWorkerCompletedEventArgs e) in C:\tom\github\flashdevelop\PluginCore\PluginCore\FRService\FRRunner.cs:line 165
---------------------------
OK   
---------------------------
```

**Comment by tom-seddon** [comment]
Wait, no I'm not - I've been building from git, but my build is 1 month old, and there've been a lot of changes to that file since. And I don't have time to update right now.

Thanks,

--Tom
