### ISSUE TITLE
FD crashes in PathModel.RemoveFile

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#2744]
What I was doing: executing a macro which writes the current document to a temp file (in the project's directory), runs an external process to format it, wait for the process to finish (FD blocks for several seconds, in this case it was >30 s since I was testing with an 80k loc file), then reloads the temp file and deletes it, then assigns the loaded text to the current document's content (this keeps the undo working). FD crashed at some point, probably after the file got deleted, or after Scintilla finished handling changing the document text.

Exception:
```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ASCompletion.Model.PathModel.RemoveFile(String fileName) in C:\project\flashdevelop\External\Plugins\ASCompletion\Model\PathModel.cs:line 587
   at ASCompletion.Model.PathModel.watcher_Deleted(Object sender, FileSystemEventArgs e) in C:\project\flashdevelop\External\Plugins\ASCompletion\Model\PathModel.cs:line 359
   at PluginCore.Bridge.WatcherEx.watcher_Deleted(Object sender, FileSystemEventArgs e) in C:\project\flashdevelop\PluginCore\PluginCore\Bridge\WatcherEx.cs:line 167
   at System.IO.FileSystemWatcher.OnDeleted(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by gene-pavlovsky** [comment]
The macro I was using (rename to `HXFormat.cs`). Uses `haxe-formatter` (`haxelib install formatter`).
[HXFormat.txt](https://github.com/fdorg/flashdevelop/files/2991552/HXFormat.txt)

For the test file I just got some large code file and duplicated it's contents until it was ~80k loc.
