### ISSUE TITLE
[Error] Path cannot be the empty string or all whitespace.

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#2748]
I tried to type `js.Lib.debug()` and on each `.` I got this error:

```
Path cannot be the empty string or all whitespace.

   at System.IO.Directory.CreateDirectory(String path)
   at PluginCore.Helpers.FileHelper.WriteFile(String file, String text, Encoding encoding, Boolean saveBOM)
   at FlashDevelop.Docking.TabbedDocument.Save(String file, String reason)
   at FlashDevelop.Docking.TabbedDocument.Save()
   at HaXeContext.HaxeComplete330.SaveFile()
   at HaXeContext.HaxeComplete.StartThread[T](HaxeCompleteResultHandler`1 callback, Func`1 resultFunc)
   at HaXeContext.HaxeComplete.GetList(HaxeCompleteResultHandler`1 callback)
   at HaXeContext.Context.ResolveDotContext(ScintillaControl sci, ASExpr expression, Boolean autoHide)
   at ASCompletion.Completion.ASComplete.HandleDotCompletion(ScintillaControl sci, Boolean autoHide, List`1 list, Comparison`1 comparison)
   at ASCompletion.Completion.ASComplete.HandleDotCompletion(ScintillaControl sci, Boolean autoHide)
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl sci, Int32 value, Boolean autoHide)
```
![image](https://user-images.githubusercontent.com/576184/55629223-fce25f80-57b2-11e9-95f3-122daa98f49e.png)

This kinda worries me, are there directories trying to be created when requesting completion?

**Comment by SlavaRa** [comment]
Do you use PostfixCompletion Plugin?

**Comment by markknol** [comment]
No

**Comment by SlavaRa** [comment]
Hmm.. ok, I have to somehow reproduce this error.

**Comment by SlavaRa** [comment]
@markknol can you try the latest development build?
http://flashdevelop.org/downloads/builds/

**Comment by markknol** [comment]
It seems to be gone now! What was wrong?

**Comment by SlavaRa** [comment]
I don't know ;( but I have seen a similar problem before.

**Comment by markknol** [comment]
Let's hope it's gone now :D have a good weekend!
