### ISSUE TITLE
[Haxe][Openfl] Exception: Length cannot be less than zero.

### ISSUE THREAD

**Issue by SlavaRa** [fdorg/flashdevelop#2749]
Openfl 8.9.0
Haxe 4.0.0-rc.2
```
Length cannot be less than zero.
Parameter name: length

   at System.String.Substring(Int32 startIndex, Int32 length)
   at HaXeContext.ExternalToolchain.Run(String command)
   at HaXeContext.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

**Comment by SlavaRa** [comment]
via #2770
