### ISSUE TITLE
UI Theme: 1 is not a supported code page.

### ISSUE THREAD

**Issue by Adolio** [fdorg/flashdevelop#2819]
Hello,

I'm using the latest flashDevelop development build & I'm getting the following error while trying to apply a Full UI Theme (via Tools/Select UI Theme...) :

```
1 is not a supported code page.
Parameter name: codepage

   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToString(Byte[] data, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToStringExt(Int32 flags, Byte[] data)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.GetNextEntry()
   at FlashDevelop.MainForm.ExtractZip(Object sender, EventArgs e)
```

Best,
Aurélien

**Comment by SlavaRa** [comment]
I can not repeat it on my latest development version :(

**Comment by SlavaRa** [comment]
What is your specific version(Help -> About FlashDevelop...)?
From where and how did you install it?
What kind of theme do you want to install?
Is the error stable?

**Comment by Adolio** [comment]
My version is `FlashDevelop 5.3.4.418 for .NET 4.0 (development#55b0322bd7)`
I have downloaded the installer from the build page: https://flashdevelop.org/downloads/builds/

I want to install the `VsDark Full Theme` (1.2) downloaded from the embedded `AppMan` tool.

The error is 100% reproduceable on my side for all Full Themes (.fdz) but UI theme are working (.fdi).
The issue seems to come while extracting the zip.
