### ISSUE TITLE
"value cannot be null" in HaXeContext.Context.GetCodeModel

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#2836]
FD version: 5.3.4.430
Haxe version: 4, RC3

1, Checkout https://github.com/GameMakerDiscord/GMEdit/commit/b289748f3dc9acfb5499b562a954f693176c7e1d
2. Open src/parsers/GmlLinter.hx
3. If the error doesn't pop up right away, add a space at L118 and hit Ctrl+S
```
System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at HaXeContext.Context.GetCodeModel(FileModel result, String src, Boolean scriptMode)
   at ASCompletion.Context.ASContext.GetCodeModel(FileModel result, String src)
   at ASCompletion.Context.ASContext.UpdateCurrentFile(Boolean updateUI)
   at ASCompletion.Context.ASContext.set_CurrentLine(Int32 value)
   at ASCompletion.Context.ASContext.SetCurrentLine(Int32 line)
   at ASCompletion.PluginMain.ContextChanged()
   at ASCompletion.PluginMain.timerPosition_Elapsed(Object sender, ElapsedEventArgs e)
```

**Comment by YellowAfterlife** [comment]
Ran with debugger and found a simpler repro:
```haxe
class Test {
    static function main() {}
}
enum abstract ABug(Int) {
	public function not_a_field():Void {};
	public var // <- start typing here
}
```
This is because the value of a non-var member is `null`.
