### ISSUE TITLE
crash when typing Map<%cursor%()

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#2858]
![fd_map_crash](https://user-images.githubusercontent.com/1420061/66037666-39540580-e521-11e9-9a32-96817de67a33.PNG)
FD version:  [https://github.com/fdorg/flashdevelop/commit/180ccdf5ca](https://github.com/fdorg/flashdevelop/commit/180ccdf5ca)
Haxe vesion: 4rc4.
Stack:
```
Object reference not set to an instance of an object.
   at ASCompletion.Completion.ASComplete.GetFunctionContext(ScintillaControl sci, Boolean autoHide) in flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2429
   at ASCompletion.Completion.ASComplete.HandleColonCompletion(ScintillaControl sci, String tail, Boolean autoHide) in flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2334
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl sci, Int32 value, Boolean autoHide) in flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 173
```

**Comment by SlavaRa** [comment]
Thx ;)
