### ISSUE TITLE
[CodeRefactor] crash after cancelled file drag-drop

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#2862]
![fd_bug_drag_cancel](https://user-images.githubusercontent.com/1420061/66066530-be0f4580-e55a-11e9-8af4-2a6c224dc502.gif)

FD version: [https://github.com/fdorg/flashdevelop/commit/107b5f80f2](https://github.com/fdorg/flashdevelop/commit/107b5f80f2)
Stack:
```
************** Exception Text **************
ProjectManager.Actions.FileActions+UserCancelException: Exception of type 'ProjectManager.Actions.FileActions+UserCancelException' was thrown.
   at ProjectManager.Actions.FileActions.Copy(String fromPath, String toPath) in e:\csharp\flashdevelop\External\Plugins\ProjectManager\Actions\FileActions.cs:line 603
   at ProjectManager.Controls.TreeView.ProjectTreeView.OnFileDrop(String[] paths, TreeNode targetNode) in e:\csharp\flashdevelop\External\Plugins\ProjectManager\Controls\TreeView\ProjectTreeView.cs:line 486


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FlashDevelop
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/FlashDevelop64.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PluginCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/PluginCore.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
AirProperties
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/AirProperties.DLL
----------------------------------------
AS2Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/AS2Context.DLL
----------------------------------------
ASCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/ASCompletion.DLL
----------------------------------------
AS3Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/AS3Context.DLL
----------------------------------------
XMLCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/XMLCompletion.DLL
----------------------------------------
Aga
    Assembly Version: 1.7.0.1
    Win32 Version: 1.7.0.1
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Aga.DLL
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ASClassWizard
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/ASClassWizard.DLL
----------------------------------------
BasicCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/BasicCompletion.DLL
----------------------------------------
BookmarkPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/BookmarkPanel.DLL
----------------------------------------
BridgeSettings
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/BridgeSettings.DLL
----------------------------------------
CodeAnalyzer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/CodeAnalyzer.DLL
----------------------------------------
CodeFormatter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/CodeFormatter.DLL
----------------------------------------
Antlr3
    Assembly Version: 3.1.3.20199
    Win32 Version: 3.1.3.20199
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Antlr3.DLL
----------------------------------------
CodeRefactor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/CodeRefactor.DLL
----------------------------------------
ProjectManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/ProjectManager.DLL
----------------------------------------
CssCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/CssCompletion.DLL
----------------------------------------
DataEncoder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/DataEncoder.DLL
----------------------------------------
EditorConfig
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/EditorConfig.DLL
----------------------------------------
fdb.j4n
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/fdb.j4n.DLL
----------------------------------------
jni4net.n-0.8.9.0
    Assembly Version: 0.8.9.0
    Win32 Version: 0.8.9.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/jni4net.n-0.8.9.0.DLL
----------------------------------------
FileExplorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/FileExplorer.DLL
----------------------------------------
FixMixedSpaces
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/FixMixedSpaces.DLL
----------------------------------------
FlashConnect
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/FlashConnect.DLL
----------------------------------------
FlashDebugger
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/FlashDebugger.DLL
----------------------------------------
FlashLogViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/FlashLogViewer.DLL
----------------------------------------
FlashViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/FlashViewer.DLL
----------------------------------------
HaXeContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/HaXeContext.DLL
----------------------------------------
LintingHelper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/LintingHelper.DLL
----------------------------------------
jni4net.n-0.8.4.0
    Assembly Version: 0.8.4.0
    Win32 Version: 0.8.4.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/jni4net.n-0.8.4.0.DLL
----------------------------------------
jni4net.n.w64.v40-0.8.9.0
    Assembly Version: 0.8.9.0
    Win32 Version: 0.8.9.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/jni4net.n.w32.v40-0.8.9.0.dll
----------------------------------------
LayoutManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/LayoutManager.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
LoomContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/LoomContext.DLL
----------------------------------------
MacroManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/MacroManager.DLL
----------------------------------------
OutputPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/OutputPanel.DLL
----------------------------------------
PHPContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/PHPContext.DLL
----------------------------------------
SwfOp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/SwfOp.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
ResultsPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/ResultsPanel.DLL
----------------------------------------
SourceControl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/SourceControl.DLL
----------------------------------------
StartPage
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/StartPage.DLL
----------------------------------------
TaskListPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/TaskListPanel.DLL
----------------------------------------
Theraot.Core
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///flashdevelop/FlashDevelop/Bin/Debug/Plugins/Theraot.Core.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
```

**Comment by SlavaRa** [comment]
https://github.com/fdorg/flashdevelop/issues/2839
