### ISSUE TITLE
Exception when copying data to clipboard outside of FD

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#2888]
I think one of the questions is why does FD even need to care about clipboard operations if it's not focused.
```
************** Exception Text **************
System.ArgumentException: Specified IDataObject does not contain any text data.
   at FlashDevelop.Managers.ClipboardTextData.Initialize(IDataObject dataObject)
   at FlashDevelop.Managers.ClipboardTextData..ctor(IDataObject dataObject)
   at FlashDevelop.Managers.ClipboardManager.HandleWndProc(Message& m)
   at FlashDevelop.MainForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by SlavaRa** [comment]
Duplicate #2597

**Comment by YellowAfterlife** [comment]
How come that bug doesn't show up when searching for "clipboard"

**Comment by SlavaRa** [comment]
I don't know :(
