### ISSUE TITLE
Import of syntax coloring

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#2890]
Installing HaxeDevelop on new laptop. I have same haxedevelop version on both laptops. I exported the syntax coloring settings, I try to open the fdz on the new laptop but get this error:

```
1 is not a supported code page.
Parameter name: codepage

   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToString(Byte[] data, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToStringExt(Int32 flags, Byte[] data)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.GetNextEntry()
   at FlashDevelop.MainForm.ExtractZip(Object sender, EventArgs e)
```

How can this be solved ?

**Comment by SlavaRa** [comment]
What version of HD?
Can you provide fdz for me?

**Comment by markknol** [comment]
latest nightly 
https://dump.stroep.nl/theme.fdz

**Comment by SlavaRa** [comment]
thx, I`ll check tonight

**Comment by markknol** [comment]
For now I unpacked the zip and put manually in user config :) that seems to work fine too.

**Comment by SlavaRa** [comment]
duplicate #2819

**Comment by SlavaRa** [comment]
@markknol can you try the latest dev build?
