### ISSUE TITLE
[Haxe4] crash at openfl::removeEventListener

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#2933]
FD crashes when trying to go to declaration (F4) at ``removeEventListener`` function:
![fd_crash_removeEventListener](https://user-images.githubusercontent.com/1420061/70233613-610d5700-1778-11ea-8014-596a71b06a57.png)
Stack:
```
************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at HaXeContext.Completion.CodeComplete.FindMemberEx(String token, ClassModel inClass, ASResult result, FlagType mask, Visibility access) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1506
   at ASCompletion.Completion.ASComplete.FindMember(String token, ClassModel inClass, ASResult result, FlagType mask, Visibility access) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 3179
   at ASCompletion.Completion.ASComplete.EvalTail(ASExpr context, FileModel inFile, ASResult head, IList`1 tokens, Boolean complete, Boolean filterVisibility) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2753
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2640
   at HaXeContext.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1206
   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4388
   at ASCompletion.Completion.ASComplete.InternalDeclarationLookup(ScintillaControl sci) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 605
   at ASCompletion.Completion.ASComplete.DeclarationLookup(ScintillaControl sci) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 572
   at ASCompletion.PluginMain.GotoDeclaration(Object sender, EventArgs e) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\PluginMain.cs:line 995
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at FlashDevelop.MainForm.ProcessCmdKey(Message& msg, Keys keyData) in e:\csharp\flashdevelop\FlashDevelop\MainForm.cs:line 1495
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at ScintillaNet.ScintillaControl.PreProcessMessage(Message& m) in e:\csharp\flashdevelop\PluginCore\ScintillaNet\ScintillaControl.cs:line 3820
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```
FD version: https://github.com/fdorg/flashdevelop/commit/bf335a72b1
Haxe: 4.0.3.
OpenFL: https://github.com/openfl/openfl/commit/51b239be50a62089ec4153ec99b10292e3338647

**Comment by Klug76** [comment]
Main.hx:
```
package;

import openfl.display.Sprite;
import openfl.Lib;
import openfl.events.Event;

class Main extends Sprite
{
	public function new()
	{
		super();
		removeEventListener(Event.CHANGE, null, false);
	}
}
```

**Comment by Klug76** [comment]
![err1](https://user-images.githubusercontent.com/1420061/70236052-97010a00-177d-11ea-8095-ba616183f628.png)
![err2](https://user-images.githubusercontent.com/1420061/70236064-9cf6eb00-177d-11ea-828f-524b37c87682.png)

**Comment by Klug76** [comment]
![err3](https://user-images.githubusercontent.com/1420061/70236345-32927a80-177e-11ea-87e9-249786800884.png)
![err4](https://user-images.githubusercontent.com/1420061/70236350-358d6b00-177e-11ea-8d57-ec6c91945411.png)
