### ISSUE TITLE
Haxe 4 new function type

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#2960]
in HaxeDevelop this works:
```haxe
class Main {
	private var _onComplete:Void->Bool;
	
	public function new(onComplete:Void->Bool) {
		_onComplete = onComplete;
	}
}
```

But this gives errors:

```haxe
class Main {
	private var _onComplete:()->Bool;
	
	public function new(onComplete:()->Bool) {
		_onComplete = onComplete;
	}
}
```
The error is 
```
Index was outside the bounds of the array.

   at HaXeContext.Model.FileParser.CleanFunctionType(String type)
   at HaXeContext.Model.FileParser.FunctionTypeToMemberModel[T](String type, ContextFeatures features, T result)
   at HaXeContext.Model.FileParser.<FinalizeModel>g__FinalizeMembers|48_0(IList`1 members)
   at HaXeContext.Model.FileParser.FinalizeModel()
   at HaXeContext.Model.FileParser.ParseSrc(FileModel fileModel, String src, Boolean allowBaReExtract)
   at HaXeContext.Model.FileParser.ParseSrc(FileModel fileModel, String src)
   at ASCompletion.Context.ASContext.GetCodeModel(FileModel result, String src, Boolean scriptMode)
   at HaXeContext.Context.GetCodeModel(FileModel result, String src, Boolean scriptMode)
   at ASCompletion.Context.ASContext.GetCodeModel(FileModel result, String src)
   at ASCompletion.Context.ASContext.UpdateCurrentFile(Boolean updateUI)
   at ASCompletion.Context.ASContext.get_CurrentMember()
   at HaXeContext.Completion.CodeComplete.OnChar(ScintillaControl sci, Int32 value, Char prevValue, Boolean autoHide)
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl sci, Int32 value, Boolean autoHide)
```

This syntax is new since Haxe 4 https://github.com/HaxeFoundation/haxe/wiki/What's-new-in-Haxe-4#new-function-type-syntax

--- 

I'm using nightly from this build: http://www.github.com/fdorg/flashdevelop/commit/10944c478d
![image](https://user-images.githubusercontent.com/576184/71676440-8cd42a80-2d80-11ea-810b-50aa60ae263f.png)

**Comment by SlavaRa** [comment]
Duplicated #2943
