### ISSUE TITLE
Null reference error in Context.LookupClass

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#2977]
```
Object reference not set to an instance of an object.

   at AS2Context.Context.LookupClass(String package, String cname, String inPackage, Boolean testSamePackage, Boolean testModule, PathModel aPath) in ...\External\Plugins\AS2Context\Context.cs:line 715
   at AS2Context.Context.GetModel(String package, String cname, String inPackage) in ...\External\Plugins\AS2Context\Context.cs:line 676
   at ASCompletion.Completion.ASComplete.ResolveType(String cname, FileModel inFile) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2982
   at ASCompletion.Completion.ASComplete.FindMemberEx(String token, ClassModel inClass, ASResult result, FlagType mask, Visibility access) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 3252
   at HaXeContext.Completion.CodeComplete.FindMemberEx(String token, ClassModel inClass, ASResult result, FlagType mask, Visibility access) in ...\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1615
   at ASCompletion.Completion.ASComplete.FindMember(String token, ClassModel inClass, ASResult result, FlagType mask, Visibility access) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 3164
   at ASCompletion.Completion.ASComplete.EvalTail(ASExpr context, FileModel inFile, ASResult head, IList`1 tokens, Boolean complete, Boolean filterVisibility) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2738
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2625
   at HaXeContext.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in ...\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1259
   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4373
   at HaXeContext.Completion.CodeComplete.InferVariableType(ScintillaControl sci, Int32 rvalueStart, MemberModel var) in ...\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 970
   at HaXeContext.Completion.CodeComplete.InferVariableType(ScintillaControl sci, String declarationLine, Int32 rvalueStart, ASExpr local, MemberModel var) in ...\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 842
   at ASCompletion.Completion.ASComplete.InferType(ScintillaControl sci, ASExpr local, MemberModel member) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 3024
   at HaXeContext.Completion.CodeComplete.InferType(ScintillaControl sci, ASExpr local, MemberModel member) in ...\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 664
   at ASCompletion.Completion.ASComplete.EvalVariable(String token, ASExpr local, FileModel inFile, ClassModel inClass) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2852
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2609
   at HaXeContext.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in ...\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1259
   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4373
   at HaXeContext.Completion.CodeComplete.InferFunctionType(ScintillaControl sci, MemberModel member) in ...\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1094
   at HaXeContext.Completion.CodeComplete.InferType(ScintillaControl sci, ASExpr local, MemberModel member) in ...\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 652
   at ASCompletion.Completion.ASComplete.InferType(ScintillaControl sci, MemberModel member) in ...\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 3003
   at ASCompletion.PluginUI.AddMembers(TreeNodeCollection tree, MemberList members) in ...\External\Plugins\ASCompletion\PluginUI.cs:line 875
   at ASCompletion.PluginUI.AddMembersSorted(TreeNodeCollection tree, MemberList members) in ...\External\Plugins\ASCompletion\PluginUI.cs:line 777
   at ASCompletion.PluginUI.RefreshView(FileModel aFile) in ...\External\Plugins\ASCompletion\PluginUI.cs:line 673
```
This errors because inPackage is null, and it can be null as it is acquired via `inFile?.package` in ASComplete.ResolveType, and inFile is given as null when that is called by a few spots in ASComplete (like [this one in stacktrace](https://github.com/fdorg/flashdevelop/blob/cc409b4192c00c74a81e73d88500977ba78c0ff2/External/Plugins/ASCompletion/Completion/ASComplete.cs#L3252)).

FD version: 5.3.4 / https://github.com/fdorg/flashdevelop/commit/cc409b4192

**Comment by SlavaRa** [comment]
@YellowAfterlife how can I reproduce it?
