### ISSUE TITLE
A doc comment with backslashed ending causes the field name to be detected as "*"

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#2978]
... and then error because the field name is being used for constructing a regex on valid assumption that it's alphanumeric
```haxe
class Main {
	static function main() {
		trace(neko.vm.Module.local().name);
	}
}
enum TokenKind {
	/** A block comment (`/* text \*\/`) */
	CommentBlock;
}
```
```
parsing "\s*for\s*\(\s**\s*in\s*" - Nested quantifier *.

   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex.Match(String input, String pattern)
   at HaXeContext.Completion.CodeComplete.InferType(ScintillaControl sci, ASExpr local, MemberModel member) in C:\Dev\Csharp\Downloads\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 661
   at ASCompletion.Completion.ASComplete.InferType(ScintillaControl sci, MemberModel member) in C:\Dev\Csharp\Downloads\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 3003
   at ASCompletion.PluginUI.AddMembers(TreeNodeCollection tree, MemberList members) in C:\Dev\Csharp\Downloads\flashdevelop\External\Plugins\ASCompletion\PluginUI.cs:line 875
   at ASCompletion.PluginUI.AddMembersSorted(TreeNodeCollection tree, MemberList members) in C:\Dev\Csharp\Downloads\flashdevelop\External\Plugins\ASCompletion\PluginUI.cs:line 777
   at ASCompletion.PluginUI.RefreshView(FileModel aFile) in C:\Dev\Csharp\Downloads\flashdevelop\External\Plugins\ASCompletion\PluginUI.cs:line 673
```
FD version: 5.3.4 / https://github.com/fdorg/flashdevelop/commit/cc409b4192

**Comment by SlavaRa** [comment]
WIP
