### ISSUE TITLE
Exceptions when launching and closing

### ISSUE THREAD

**Issue by B-Interactive** [fdorg/flashdevelop#2989]
This issue relates to **FlashDevelop 5.3.4.517 for .NET 4.8 (development#1e62a1d8fa)**, under Windows 10 64bit. 
I've uninstalled the prior version, installed the new, then deleted FleshDevelop's folder within AppData before each launch test (%HOMEPATH%\AppData\Local\FlashDevelop).  These exceptions were pulled from **Exceptions.log**.  No project is being opened, only launching the app.

When **launching FlashDevelop 32bit**, I'm presented with these exceptions:

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateCustomDocument(Control ctrl)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateCustomDocument(Control ctrl)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```

When **closing FlashDevelop 32bit**, I'm presented with these exceptions:

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateCustomDocument(Control ctrl)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```

When **launching FlashDevelop 64bit**, I'm presented with these exceptions:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```

When **closing FlashDevelop 64bit**, I'm presented with this exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.Docking.TabbedDocument.AddEditorControls(String file, String text, Int32 codepage)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```

**Comment by B-Interactive** [comment]
When I opened FlashDevelop today (next day, effectively after reboot), I'm not faced with any of these issues anymore.

Perhaps all that was needed was a reboot?
