### ISSUE TITLE
Wrong method of getting directory names

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#2994]
FD uses the wrong (for windows API) method of getting directory names (probably the code is copied from asp.net).
An example of one of the bad entries:
```
                string url = Assembly.GetEntryAssembly().GetName().CodeBase;
                Uri uri = new Uri(url);
                return Path.GetDirectoryName(uri.LocalPath);
```
This will not work properly if the name contains characters that are allowed for files but special for Uri (for example, '#')'.

**Comment by Klug76** [comment]
Steps to reproduce bug:
1 Install FlashDevelop in "c:/progs#/fd"
2 Launch FlashDevelop
3 Create or open any haxe project
4 Try to build a project:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at FDBuild.Program.Main(String[] args)
```
Tested with version: https://github.com/fdorg/flashdevelop/commit/3ab79ffdbe
