### ISSUE TITLE
[Haxe3] Completion breaks when you have unsaved new hx file

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#3025]
Completion is completely broken when you have a unsaved new file open.

Demonstration:

![haxedevelop-new-hx-file-completion-error](https://user-images.githubusercontent.com/576184/79569691-5ebcf100-80b8-11ea-97e4-b18f82b329d1.gif)

The error:
```
Path cannot be the empty string or all whitespace.

   at System.IO.Directory.CreateDirectory(String path)
   at PluginCore.Helpers.FileHelper.WriteFile(String file, String text, Encoding encoding, Boolean saveBOM)
   at FlashDevelop.Docking.TabbedDocument.Save(String file, String reason)
   at HaXeContext.HaxeComplete330.SaveFile()
   at HaXeContext.HaxeComplete.StartThread[T](HaxeCompleteResultHandler`1 callback, Func`1 resultFunc)
   at HaXeContext.HaxeComplete.GetList(HaxeCompleteResultHandler`1 callback)
   at HaXeContext.Context.ResolveDotContext(ScintillaControl sci, ASExpr expression, Boolean autoHide)
   at ASCompletion.Completion.ASComplete.HandleDotCompletion(ScintillaControl sci, Boolean autoHide, List`1 list, Comparison`1 comparison)
   at ASCompletion.Completion.ASComplete.HandleDotCompletion(ScintillaControl sci, Boolean autoHide)
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl sci, Int32 value, Boolean autoHide)
```

---
Version info:

I use a nightly build from this version:
https://github.com/fdorg/flashdevelop/commit/7325aacd84

![image](https://user-images.githubusercontent.com/576184/79569806-a17ec900-80b8-11ea-9838-41af6de684d0.png)

**Comment by SlavaRa** [comment]
in progress

**Comment by SlavaRa** [comment]
@markknol hi, can you check the latest development build?
https://flashdevelop.org/downloads/builds/
