### ISSUE TITLE
Exception while typing s="

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#3026]
FD crashed while typing
```
	function run_Command1()
	{
		var s = "
	}
```
after the qoute. Unfortunately it cannot be reproduced with same text.
Stack:
```
startIndex cannot be larger than length of string.
Parameter name: startIndex

   at System.String.Substring(Int32 startIndex, Int32 length)
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2557
   at HaXeContext.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1266
   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4346
   at HaXeContext.Completion.CodeComplete.InferVariableType(ScintillaControl sci, Int32 rvalueStart, MemberModel var) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 971
   at HaXeContext.Completion.CodeComplete.InferVariableType(ScintillaControl sci, String declarationLine, Int32 rvalueStart, ASExpr local, MemberModel var) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 843
   at ASCompletion.Completion.ASComplete.InferType(ScintillaControl sci, ASExpr local, MemberModel member) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2997
   at HaXeContext.Completion.CodeComplete.InferType(ScintillaControl sci, ASExpr local, MemberModel member) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 658
   at ASCompletion.Completion.ASComplete.EvalVariable(String token, ASExpr local, FileModel inFile, ClassModel inClass) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2825
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2582
   at HaXeContext.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1266
   at ASCompletion.Completion.ASComplete.GetExpressionType(ScintillaControl sci, Int32 position, Boolean filterVisibility, Boolean ignoreWhiteSpace) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 4346
   at HaXeContext.Completion.CodeComplete.HandleAssignCompletion(ScintillaControl sci, Int32 position, Boolean autoHide) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 289
   at HaXeContext.Completion.CodeComplete.HandleWhiteSpaceCompletion(ScintillaControl sci, Int32 position, String wordLeft, Boolean autoHide) in e:\csharp\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 180
   at ASCompletion.Completion.ASComplete.HandleWhiteSpaceCompletion(ScintillaControl sci, Int32 position, Boolean autoHide) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2422
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl sci, Int32 value, Boolean autoHide) in e:\csharp\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 160
```

Haxe: 4.0.5
FD: https://github.com/fdorg/flashdevelop/commit/7325aacd844e831238304012f217442815d1b4b3

**Comment by SlavaRa** [comment]
fixed via #3032
