### ISSUE TITLE
Haxedevelop not working since recently

### ISSUE THREAD

**Issue by datee** [fdorg/flashdevelop#3034]
So it seems a recent window supdate or something broke Haxedevelop altogether.
I am unable to start it at all now, just get alot of exceptions when it launches.

Have tried to remove and reinstall everything many times, but no luck. 
Could be related to : https://github.com/fdorg/flashdevelop/issues/3033

Haxedevelop is my main coding tool, so im getting a bit of panic :)

The problem is persistant on Win 10 with 5.3.4 and older versions also.
Release build (2 year old) worked like normal.

Here is the exceptions log (from today)
```

08.06.2020 09:17:24

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)

08.06.2020 09:17:25

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)

08.06.2020 09:17:26

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)

08.06.2020 09:17:26

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)

08.06.2020 09:17:38

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)

08.06.2020 09:17:39

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)

```

**Comment by hoangdung-qbt** [comment]
It worked for me -  uninstall Flash Develop and delete all setting files in folder C:\Users\Name\AppData\Local and then install the new one, a little bit annoying!

**Comment by hachigoro** [comment]
I tried that several times and didn't work for me. What Windows version do you have? I have 1903.

**Comment by hoangdung-qbt** [comment]
I'm using Windows 10, big update June 2020, you might check the version of .Net FW or try to disable Flash ActiveX Plug-in of Internet Explorer.

**Comment by datee** [comment]
Uninstalling and reinstalling does not help - the issue seems to be related to some of the settings / temp files being corrupted and cant be read properly on the next start. Deleting temporary files and settings each time before starting FD/HD solves the issue but that is very annoying....

**Comment by hoangdung-qbt** [comment]
Something is still not clear and reaches to my limitations. but following all these steps I'm now using Flash Develop as usual! I did not test with Haxe Develop!. Please keep this project alive. It is still the best choice for Windows users when working with Haxe and AS3!

**Comment by datee** [comment]
Just tried a fresh install from the latest commits, its completely broken for me. Unable to start at all! :(

**Comment by hoangdung-qbt** [comment]
Uninstall and delete all setting files of the nightly then restart PC and re-install the stable version 5.3.3. it worked for me now but I still do not know about the next updates of Windows! - Just think about the situations that we would repeat all these steps over and over. :)

**Comment by datee** [comment]
5.3.3 works, but that is over 2 years old... I hope someone can look into this issue

**Comment by SlavaRa** [comment]
5.3.4.? x86 or x64?

**Comment by datee** [comment]
> 5.3.4.? x86 or x64?

Yes, 5.3.4, latest dev builds - x86 and x64 both. Tried older dev builds, same issue also. I think the problem occured after Win10 May update.

**Comment by SlavaRa** [comment]
please say the exact numbers, i.e 5.3.4.545, your lastest and mine may not match

**Comment by datee** [comment]
Yes - im using 5.3.4.545

**Comment by SlavaRa** [comment]
which .net is installed in the your system?

**Comment by datee** [comment]
I have found a way to start it without exceptions though : 
Delete the following files / folders and it starts without error
-Settings/Recovery
-Settings/SessionData.fdb
-Settings/SettingData.fdb
-Settings/UserArgData.fda

This must be done before each time HD starts..

As for the .net version it is 4.8 - Win 10 May 2019 update - 4.8.4180.00

**Comment by hachigoro** [comment]
For me it's also crashing for version 5.3.4.545.
I have Windows 10 version 1903, and my .NET is 4.8.03752

**Comment by hachigoro** [comment]
I got a windows update that included update for the .NET framework, and the problem with FD is solved :)

**Comment by SlavaRa** [comment]
dupliceted #3036
