### ISSUE TITLE
Can't launch FlashDevelop anymore, error Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ugotopia123** [fdorg/flashdevelop#3061]
Upon launch (both regular launch and launching as administrator) on Windows with the most recent development release I get this error window popping up:

```
Object reference not set to an instance of an object.

   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

The only option I get is "Continue" as the "Exit" button is grayed out. Clicking continue pops up another error box, and another, continuing for several error boxes before the program launches. Upon trying to do anything (even closing the program), yet another series or error boxes appears.

I'll give the entire error rundown here from initial launch to close:
```
Object reference not set to an instance of an object.

   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```
```
Object reference not set to an instance of an object.

   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```
```
Object reference not set to an instance of an object.

   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```
```
Object reference not set to an instance of an object.

   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```
```
FlashDebugger.BreakPointInfo cannot be serialized because it does not have a parameterless constructor.

   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError)
   at System.Xml.Serialization.ModelScope.GetTypeModel(Type type, Boolean directReference)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer.FromTypes(Type[] types)
   at FlashDebugger.Util.SerializeXML`1.LoadFile(String filename)
   at FlashDebugger.BreakPointManager.Load(String filePath)
   at FlashDebugger.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```
```
Object reference not set to an instance of an object.

   at CodeRefactor.Provider.RefactoringHelper.IsProjectRelatedFile(IProject project, String file)
   at CodeRefactor.PluginMain.IsValidFile(String file)
   at CodeRefactor.PluginMain.IsValidForMove(String oldPath)
   at CodeRefactor.PluginMain.OnTreeSelectionChanged()
   at CodeRefactor.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

The program "launches" at this point but I cannot perform any action. Even trying to close the window gives errors. Here's the errors after I press the X button to try to close the program:
```
Object reference not set to an instance of an object.

   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at StartPage.PluginMain.CreateStartPage()
   at StartPage.PluginMain.ShowStartPage()
   at StartPage.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```
```
Object reference not set to an instance of an object.

   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at FlashDevelop.MainForm.CreateEditableDocument(String file, String text, Int32 codepage)
```
```
FlashDebugger.BreakPointInfo cannot be serialized because it does not have a parameterless constructor.

   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError)
   at System.Xml.Serialization.ModelScope.GetTypeModel(Type type, Boolean directReference)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer.FromTypes(Type[] types)
   at FlashDebugger.Util.SerializeXML`1.SaveFile(String filename, T obj)
   at FlashDebugger.BreakPointManager.Save(String filePath)
   at FlashDebugger.PluginMain.Dispose()
   at FlashDevelop.Utilities.PluginServices.DisposePlugins()
```

At this point the program finally closes. What the heck is going on? I tried reinstalling the program but that didn't fix the problem. I've also tried running both the "FlashDevelop.exe" and "FlashDevelop64.exe", both normally and in administrator mode.

**Comment by ugotopia123** [comment]
I suspect a Windows update that occurred while I was sleeping might be the culprit. FlashDevelop was working fine yesterday and it's not working today. I'll try to roll back the updates and report if I made any progress.

The updates in question are the KB4576478 and KB4571756

**Comment by ugotopia123** [comment]
Welp that was fast. Removing both updates and restarting the computer fixed the issue. Hopefully this thread helps others in case they find themselves in the same predicament.
