### ISSUE TITLE
Crash: startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by Klug76** [fdorg/flashdevelop#3227]
FD crashes when trying to type ``a=".``:
```haxe
package ;

class Foo
{
	var a=".
	public function new()
	{}
}
```

```
startIndex cannot be larger than length of string.
Parameter name: startIndex

   at System.String.Substring(Int32 startIndex, Int32 length)
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in ...\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2532
   at HaXeContext.Completion.CodeComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction, Boolean filterVisibility) in ...\flashdevelop\External\Plugins\HaXeContext\Completion\CodeComplete.cs:line 1316
   at ASCompletion.Completion.ASComplete.EvalExpression(String expression, ASExpr context, FileModel inFile, ClassModel inClass, Boolean complete, Boolean asFunction) in ...\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 2494
   at ASCompletion.Completion.ASComplete.HandleDotCompletion(ScintillaControl sci, Boolean autoHide, List`1 list, Comparison`1 comparison) in ...\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 1978
   at ASCompletion.Completion.ASComplete.HandleDotCompletion(ScintillaControl sci, Boolean autoHide) in ...\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 1864
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl sci, Int32 value, Boolean autoHide) in ...\flashdevelop\External\Plugins\ASCompletion\Completion\ASComplete.cs:line 153
```
FD: https://github.com/fdorg/flashdevelop/commit/c4264e9f73
Haxe: 4.1.5

**Comment by SlavaRa** [comment]
Regression #2750
