### ISSUE TITLE
Error when saving [model] AS3 file

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#614]
When you navigate to declaration of a Flash API member or SWC member, it opens into a [model] AS3 file. If you modify this file and try to save it, you get this:

	Illegal characters in path.

	   at System.Security.Permissions.FileIOPermission.HasIllegalCharacters(String[] str)
	   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
	   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, AccessControlActions control, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
	   at System.IO.StreamWriter.CreateFile(String path, Boolean append)
	   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
	   at System.IO.StreamWriter..ctor(String path, Boolean append)
	   at PluginCore.Helpers.FileHelper.WriteFile(String file, String text, Encoding encoding, Boolean saveBOM)
	   at FlashDevelop.Docking.TabbedDocument.Save(String file)
	   at FlashDevelop.Docking.TabbedDocument.Save()
	   at FlashDevelop.MainForm.Save(Object sender, EventArgs e)

Ideally model files should not save. Either in `TabbedDocument.Save` or `FileHelper.WriteFile` there should be a check to prevent saving such non-existent files.

**Comment by Meychi** [comment]
Fixed for FD5.
