### ISSUE TITLE
[Haxe] Autocomplete exception

### ISSUE THREAD

**Issue by boolean0101** [fdorg/flashdevelop#688]
When Haxe code completion is turned on, FD crashes very often while I'm typing. 

For example, if I'm trying to type "FlxG.width", when I type the period and autocomplete tries to show me the options, FD crashes on me. 

The error is in this file: https://searchcode.com/codesearch/view/33620881
edit: https://github.com/fdorg/flashdevelop/blob/development/External/Plugins/HaXeContext/Completion/CompilerCompletionHandler.cs

System.NullReferenceException was unhandled
  Message=Object reference not set to an instance of an object.
  Source=System
  StackTrace:
       at System.Diagnostics.Process.Close()
       at HaXeContext.CompilerCompletionHandler.GetCompletion(String[] args)
       at HaXeContext.HaxeComplete.<>c__DisplayClass1.<GetList>b__0(Object _)
       at System.Threading._ThreadPoolWaitCallback.WaitCallback_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_ThreadPoolWaitCallback tpWaitCallBack)
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(Object state)
  InnerException:

**Comment by Gama11** [comment]
All I get when for that URL is a blank page.

What FD version are you using?

**Comment by boolean0101** [comment]
Oh I didn't realize the URL was temporary. The actual URL is: https://github.com/fdorg/flashdevelop/blob/development/External/Plugins/HaXeContext/Completion/CompilerCompletionHandler.cs

As for my version, it's 4.7.2.8.

**Comment by elsassph** [comment]
That's a bit strange to have an error in this system call, but a try/catch should do the trick.

**Comment by boolean0101** [comment]
Just got the latest build and that seems to have fixed it, cheers!
