### ISSUE TITLE
[haxe] FD tries to show up completion for string interpolation in docs, errors.

### ISSUE THREAD

**Issue by YellowAfterlife** [fdorg/flashdevelop#772]
Say, if you have some
```haxe
/// '
static function main() { }
```
the moment you insert a "$" after that single quote, you get this exception:
```
Object reference not set to an instance of an object.

   at ASCompletion.Completion.ASComplete.HandleInterpolationCompletion(ScintillaControl sci, Boolean autoHide, Boolean expressions)
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl Sci, Int32 Value, Boolean autoHide)
```

**Comment by Gama11** [comment]
Ouch.
