### ISSUE TITLE
Error on opening FlashDevelop.exe

### ISSUE THREAD

**Issue by beneyal** [fdorg/flashdevelop#860]
I downloaded FlashDevelop-5.0.1.zip, extracted it to a folder, and when I open FlashDevelop.exe, I get the following error message:

```
Customized cultures cannot be passed by LCID, only by name.

   at System.Globalization.CompareInfo.GetCompareInfoWithPrefixedLcid(Int32 cultureKey, Int32 prefix)
   at System.Globalization.CultureInfo.get_CompareInfo()
   at System.String.StartsWith(String value, Boolean ignoreCase, CultureInfo culture)
   at FlashDevelop.Managers.ThemeManager.LoadTheme(String file)
```

I can click "Continue" ("Exit" grayed out), which just pops the error message again. After 5 clicks on "Continue", I can finally click "Exit".

Other details:
OS: Windows 10 Education x64
Java: 32- and 64-bit JRE 1.8.0u60
.NET Framework: 2.0, 3.0, 3.5, 4.6 installed

**Comment by beneyal** [comment]
Solved.

I was using a locate of "English (World)", and customized it. After changing the locale to "English (United States)", it works.

Funny thing: I installed Visual Studio in order to try and fix the problem. Trying to install Git tools for VS produced the same error message.
